<?php
/**
 * Created by PhpStorm.
 * User: admin
 * Date: 2019/5/6
 * Time: 15:44
 */

namespace app\admin\controller;


use app\common\helper\Category as CategoryHelper;
use app\common\models\Category as CategoryModel;
use think\Controller;
use think\facade\Config;
use think\facade\Session;

/**
 * Class Base
 * @package app\admin\controller
 */
class Base extends Controller
{
    protected $toLevel;
    protected $backendPrefix;
    protected $websiteName; //所有的页面的后缀；

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $category = (new CategoryModel())->getCategory()->toArray();
        $this->toLevel = CategoryHelper::toLevel($category, '-', 0, 0);
        $this->backendPrefix = Config::get('app.backend_prefix');
        $this->websiteName=Config::get('app.website_name');
        $this->assign('backendPrefix', $this->backendPrefix);
        $this->assign('app_name', $this->websiteName);
        if (Session::has('adminUser', 'admin')) {
            $session = Session::get('adminUser', 'admin');
            return $this->assign('session', $session);
        } else {
            return $this->redirect($this->backendPrefix . '/wavlink/login.html');
        }
    }
}