<?php
/**
 * Created by PhpStorm.
 * User: admin
 * Date: 2019/5/5
 * Time: 15:02
 */

namespace app\admin\controller;

use think\Request;
use app\common\models\Files as FilesModel;
use think\Route;

/**
 * Class Index
 * @package app\admin\controller
 */
class Files extends Base
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * @return mixed
     */
    public function index()
    {
        $data = (new FilesModel())->getFiles();
        $count = $data->count();
        return $this->fetch('',[
            'data' => $data,
            'count' => $count
        ]);
    }

    /**
     * @return mixed
     */
    public function add()
    {
        if (Request()->isGet()) {
            return $this->fetch('', [
                'to_level' => $this->toLevel,
            ]);
        }
        if (Request()->isPost()) {
            $data = input('post.');
            return (new FilesModel())->saveData($data);
        }
    }
    public function edit($id){
        if(Request()->isGet()){
            $data=(new FilesModel())->getDataById($id);
            return $this->fetch('',[
                'to_level'=>$this->toLevel,
                'data' =>$data
            ]);
        }
        if(Request()->isPost()){
            $data= input('post.');
            return (new FilesModel())->saveData($data);
        }
    }
}