<?php
/**
 * Created by PhpStorm.
 * User: admin
 * Date: 2019/6/25
 * Time: 11:26
 */

namespace app\home\controller;

/***
 * Class Article
 * @package app\home\controller
 */
class Article extends Base
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    public function index(){

    }
}